format = '''(
[○](bold green) $cmd_duration
)
[](bold white)
[●](bold white) $username@$hostname :$directory $os(
[●](bold white) $git_branch$git_status $git_commit $git_metrics $git_state)
$character '''

scan_timeout = 10
add_newline = false

[os]
format = '\([$symbol( $codename)( $edition Edition)( Ver. $version)]($style)\)'
disabled = false

[os.symbols]
Arch = "󰣇"
Ubuntu = ""
Alpine = ""
Amazon = ""
CentOS = ""
Android = ""
Artix = ""
Debian = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = ""
Gentoo = ""
Illumos = ""
Linux = ""
Macos = "󰇄"
Manjaro = ""
Mint = "󰣭"
NixOS = "󱄅"
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Solus = ""


[character]
success_symbol = '[○](bold green)'
error_symbol = '[○](bold red)'
format = '$symbol'

[username]
show_always = true
format = '[$user]($style)'
style_user = 'bold yellow'
style_root = 'bold dimmed red'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'
style = 'bold yellow'

[cmd_duration]
style = 'bold dimmed green'

[sudo]
disabled = false
style = 'bold dimmed red'
format = '\([sudoable]($style)\)'

[directory]
truncate_to_repo = false
truncation_symbol = '../'
style = "bold yellow"

[git_branch]
always_show_remote = true
style = "cyan"

[git_status]
conflicted = '!${count}'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇡${ahead_count} ⇣${behind_count}'
untracked = '${count}U'
stashed = '${count}S'
up_to_date = '✓'
modified = '${count}M'
staged = '+${count}'
renamed = '${count}R'
deleted = '${count}D'
format = '([\[ ($ahead_behind )($conflicted )($stashed )($deleted )($renamed )($modified )($staged )($untracked )\]]($style))'
disabled = false

[git_commit]
commit_hash_length = 6
format = '[\($hash$tag\)]($style)'
style = "bold green"
only_detached = false
tag_disabled = false

[git_metrics]
disabled = false
